### ISSUE TITLE
Timer is Not working 

### ISSUE THREAD

**Issue by theRealGupta** [innoj/CountdownTimer#1]
The timer is Not working when an app in the **background**. And Progress Bar Is disappear when I am coming from Background to Foreground.

**Comment by anupgupta-arg** [comment]
![whatsapp image 2018-05-05 at 1 25 35 am](https://user-images.githubusercontent.com/6472263/39649603-eb5af856-5003-11e8-94a1-4a8a63c839fb.jpeg)

**Comment by MikhailBaranau** [comment]
@anupgupta-arg did you fixed it?
